修复datanode stop 之后start 和namenode不是一个clusterId

diff --git a/hadoop3/docker-compose.yaml b/hadoop3/docker-compose.yaml
--- a/hadoop3/docker-compose.yaml
+++ b/hadoop3/docker-compose.yaml
@@ -1,4 +1,3 @@
-version: '3.8'
 
 networks:
   hadoop-network:
@@ -12,10 +11,11 @@ volumes:
   hbase_master_data:
   hbase_regionserver_data:
   zookeeper_data:
-  zookeeper_logs:
-  hive_metastore_db_data:
+  zookeeper_log:
+  zookeeper_secrets:
+  hive_metastore_db_lib:
   hive_metastore_data:
-    
+  hdfs_init_data:
 
 services:
   # ZooKeeper服务
@@ -32,7 +32,8 @@ services:
       ZOOKEEPER_TICK_TIME: 2000
     volumes:
       - zookeeper_data:/var/lib/zookeeper/data
-      - zookeeper_logs:/var/lib/zookeeper/log
+      - zookeeper_log:/var/lib/zookeeper/log
+      - zookeeper_secrets:/etc/zookeeper/secrets
 
   # HDFS NameNode服务
   namenode:
@@ -45,12 +46,21 @@ services:
       - "9870:9870"  # NameNode Web UI
       - "9000:9000"  # HDFS RPC端口
     volumes:
-      - namenode_data:/hadoop/dfs/name
+      - namenode_data:/data
     env_file:
       - ./config
     environment:
-      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
-    command: ["hdfs", "namenode"]
+      ENSURE_NAMENODE_DIR: "/data"
+    command: |
+      sh -c "
+      if [ ! -f /data/.formatted ]; then
+        echo 'Formatting NameNode for the first time...'
+        hdfs namenode -format -nonInteractive;
+        touch /data/.formatted;
+      else
+        echo 'Skipping formatting, using existing data.';
+      fi
+      hdfs namenode;"
     depends_on:
       - zookeeper
 
@@ -62,7 +72,7 @@ services:
     networks:
       - hadoop-network
     volumes:
-      - datanode_data:/hadoop/dfs/data
+      - datanode_data:/data
     env_file:
       - ./config
     command: ["hdfs", "datanode"]
@@ -80,7 +90,8 @@ services:
       - "8088:8088"  # ResourceManager Web UI
     env_file:
       - ./config
-
+    volumes:
+      - resourcemanager_data:/data
     command: ["yarn", "resourcemanager"]
     depends_on:
       - namenode
@@ -94,7 +105,7 @@ services:
     networks:
       - hadoop-network
     volumes:
-      - nodemanager_data:/hadoop/yarn/log
+      - nodemanager_data:/data
     env_file:
       - ./config
     command: ["yarn", "nodemanager"]
@@ -111,7 +122,7 @@ services:
     ports:
       - "3307:3306"
     volumes:
-      - hive_metastore_db_data:/var/lib/mysql
+      - hive_metastore_db_lib:/var/lib/mysql
     environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=hive
@@ -160,8 +171,8 @@ services:
     networks:
       - hadoop-network
     ports:
-      - "10000:10000"  # HiveServer2 Thrift端口
-      - "10002:10002"  # HiveServer2 HTTP端口
+      - "10000:10000"
+      - "10002:10002"
     environment:
       - HIVE_METASTOREURIS=thrift://hive-metastore:9083
       - HIVE_DBSERVER2_HOST=hive-server2
@@ -176,46 +187,6 @@ services:
     depends_on:
       - hive-metastore
 
-#  # HBase Master服务
-#  hbase-master:
-#    image: bde2020/hbase:2.4.14-hadoop3
-#    container_name: hbase-master
-#    hostname: hbase-master
-#    networks:
-#      - hadoop-network
-#    ports:
-#      - "16000:16000"  # HBase Master端口
-#      - "16010:16010"  # HBase Master Web UI
-#    volumes:
-#      - hbase_master_data:/hbase-data
-#    environment:
-#      - HBASE_CLUSTER_DISTRIBUTED=true
-#      - HBASE_MANAGES_ZK=false
-#      - ZOOKEEPER_QUORUM=zookeeper
-#    command: ["hbase", "master", "start"]
-#    depends_on:
-#      - zookeeper
-#
-#  # HBase RegionServer服务
-#  hbase-regionserver:
-#    image: bde2020/hbase:2.4.14-hadoop3
-#    container_name: hbase-regionserver
-#    hostname: hbase-regionserver
-#    networks:
-#      - hadoop-network
-#    ports:
-#      - "16020:16020"  # HBase RegionServer端口
-#      - "16030:16030"  # HBase RegionServer Web UI
-#    volumes:
-#      - hbase_regionserver_data:/hbase-data
-#    environment:
-#      - HBASE_CLUSTER_DISTRIBUTED=true
-#      - HBASE_MANAGES_ZK=false
-#      - ZOOKEEPER_QUORUM=zookeeper
-#    command: ["hbase", "regionserver", "start"]
-#    depends_on:
-#      - hbase-master
-
   # Spark Master服务
   spark-master:
     image: bitnami/spark:3.4.1
@@ -224,8 +195,8 @@ services:
     networks:
       - hadoop-network
     ports:
-      - "8080:8080"  # Spark Master Web UI
-      - "7077:7077"  # Spark Master端口
+      - "8080:8080"
+      - "7077:7077"
     environment:
       - SPARK_MODE=master
       - SPARK_RPC_AUTHENTICATION_ENABLED=false
@@ -267,7 +238,7 @@ services:
     networks:
       - hadoop-network
     ports:
-      - "18080:18080"  # Spark History Server Web UI
+      - "18080:18080"
     environment:
       - SPARK_MODE=history-server
       - SPARK_HISTORY_FS_LOGDIR=hdfs://namenode:9000/spark-events
@@ -276,26 +247,31 @@ services:
     depends_on:
       - namenode
 
-#  # 初始化HDFS目录的服务
-#  hdfs-init:
-#    image: apache/hadoop:3.3.6
-#    container_name: hdfs-init
-#    hostname: hdfs-init
-#    networks:
-#      - hadoop-network
-#    command: |
-#      sh -c "
-#      echo 'Waiting for namenode to be ready...'
-#      sleep 30  # 增加等待时间
-#      while ! curl -s http://namenode:9870/ >/dev/null; do sleep 1; done;
-#      hdfs dfs -mkdir -p /user/hive/warehouse;
-#      hdfs dfs -mkdir -p /spark-events;
-#      hdfs dfs -mkdir -p /tmp;
-#      hdfs dfs -chmod g+w /user/hive/warehouse;
-#      hdfs dfs -chmod g+w /spark-events;
-#      hdfs dfs -chmod g+w /tmp;
-#      echo 'HDFS directories initialized'
-#      "
-#    depends_on:
-#      - namenode
-#      - datanode
+  # 初始化HDFS目录的服务
+  hdfs-init:
+    image: apache/hadoop:3.3.6
+    container_name: hdfs-init
+    hostname: hdfs-init
+    volumes:
+      - hdfs_init_data:/data
+    networks:
+      - hadoop-network
+    user: root
+    command: |
+      sh -c "
+      echo 'Waiting for namenode to be ready...'
+      sleep 30
+      while ! curl -s http://namenode:9870/ >/dev/null; do sleep 1; done;
+
+      echo 'Creating required HDFS directories...'
+      hdfs dfs -mkdir -p /user/hive/warehouse && \
+      hdfs dfs -mkdir -p /spark-events && \
+      hdfs dfs -mkdir -p /tmp && \
+      hdfs dfs -chmod g+w /user/hive/warehouse && \
+      hdfs dfs -chmod g+w /spark-events && \
+      hdfs dfs -chmod g+w /tmp && \
+      echo 'HDFS directories initialized successfully.'
+      "
+    depends_on:
+      - namenode
+      - datanode
